### ISSUE TITLE
CostDetails: The column 'PricingModel' of the table wasn't found

### ISSUE THREAD

**Issue by chrislittle** [flanakin/cost-management-powerbi#1]
I'm trying to test this on an MCA and have set both the billing profile ID value & the scope to Billing Profile Id.  I'm an owner of the MCA billing account RBAC wise. 

Expression.Error: The column 'PricingModel' of the table wasn't found.
Details:
    PricingModel

is there something outside the docs that need to be in place?

**Comment by flanakin** [comment]
These were based on the Cost Management template app, which only supported EA. MCA uses different casing for column names and I haven't updated them to support MCA. I've been working towards that in another project: https://aka.ms/finops/hubs. We're getting pretty close, but not quite there yet. I'm hoping to have an update in July.

Barring that, I'll keep this open in case I have time to add support for MCA.

**Comment by flanakin** [comment]
Please try again with the latest reports. I don't have a good MCA test account but was able to do some light validation. Please let me know if you run into any issues. I'd especially like feedback about the FOCUS report and the column names and values you see there as they're part of an open specification for cross cloud data.
