### ISSUE TITLE
DataSourceError: Duplicate Values

### ISSUE THREAD

**Issue by lkshck** [flanakin/cost-management-powerbi#2]
Hey, I got the following Error after connecting an enterprise agreement.

`Data source error:	Column 'totalCostWithReservedInstances' in Table 'RI recommendations (single)' contains a duplicate value '17.4407854623408' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table. Table: RI recommendations (single).`

 Is there anything I can adjust on my side?

**Comment by flanakin** [comment]
This looks like there's a relationship setup on that column. 

Go to Modeling > Manage relationships and make sure totalCostWithReservedInstances is not selected:
![image](https://github.com/flanakin/cost-management-powerbi/assets/399533/4e2dfc55-6f19-4045-8077-13b465dcd242)

For good measure, go ahead and delete that relationship. (It was probably auto-detected.) I've also removed it from the report. Let me know if that fixes it for you!

(And sorry for the delayed response! I've been hyper-focused on [FinOps X](https://x.finops.org) for the past few weeks.)

**Comment by lkshck** [comment]
@flanakin Works, thank you!
