### ISSUE TITLE
Load errors using Cost and Commit templates with MCA

### ISSUE THREAD

**Issue by kbkrueger** [flanakin/cost-management-powerbi#3]
Hello! I'm trying to use the Cost Summary and Commitment Discount templates for an MCA. I'm able to connect with Billing Profile Id, but I get a few Load errors (added screenshot from Commitment Discount). I know the App doesn't work with MCA accounts, but are the other two supposed to?

![Screenshot 2023-07-05 173725](https://github.com/flanakin/cost-management-powerbi/assets/128621878/e3324884-4824-4dcc-a792-99758e11a902)

**Comment by flanakin** [comment]
MCA is not supported yet. These were based on the Cost Management template app that was designed for EA. Unfortunately, MCA fields are all different. I'm working on a normalized version to demonstrate FOCUS, which should work with MCA. Stay tuned...

**Comment by flanakin** [comment]
Please try again with the latest reports. I don't have a good MCA test account, but was able to do some light validation. Please let me know if you run into any issues. I'd especially like feedback about the FOCUS report and the column names and values you see there as they're part of an open specification for cross cloud data.

**Comment by flanakin** [comment]
Discovered an issue with the Commitment discounts report for MCA. Reopening this to track a fix.
