### ISSUE TITLE
FOCUS Report Error

### ISSUE THREAD

**Issue by chrislittle** [flanakin/cost-management-powerbi#4]
Trying the new FOCUS report with an MCA. Errors with statement:

```
FOCUS
The name 'mf_RetailCost' is already used for a column on table 'FOCUS'. Choose a different name.
```

CostSummary report works fine.

**Comment by flanakin** [comment]
Looks like Missed something when copying queries between reports 🤦‍♂️ Thanks for reporting! It'll be fixed shortly...

**Comment by flanakin** [comment]
@chrislittle should be fixed now. Thanks again for reporting this!
