### ISSUE TITLE
Credentials for MCA not working

### ISSUE THREAD

**Issue by kbkrueger** [flanakin/cost-management-powerbi#5]
Attempting to view the Cost Summary or Commitment PBIX files using MCA Billing Acct ID and Billing Profile ID are leading to the errors attached. (Credentials are valid and work with other functioning PBI reports)

![Screenshot 2023-07-10 142957](https://github.com/flanakin/cost-management-powerbi/assets/128621878/813c994f-633e-4acc-aea7-c671fecf30b2)

![Screenshot 2023-07-10 145158](https://github.com/flanakin/cost-management-powerbi/assets/128621878/a355ccaf-87ac-41a0-9288-be3c7113e3c0)

**Comment by flanakin** [comment]
Are you sure you're connecting to MCA? That error looks like you're connecting with an EA enrollment. Could you be using the wrong credentials for the EA account? Email me at micflan@ms and we can find some time to debug together. Not sure how to debug it remotely.

**Comment by flanakin** [comment]
For others: Turns out the issue was mismatched credentials. I'll use this issue to track adding some extra validation around parameters.
